

--watch-later-options=secondary-sid,sub-visibility,sub-border-size,sub-ass-override,border,contrast,brightness,gamma,saturation,hue,video-zoom,video-rotate,panscan,speed,audio,sub,audio-delay,sub-pos,sub-scale,sub-delay,sub-speed,volume,start




#Пути
--script-opts=ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"
--screenshot-directory=~~desktop/screenshot


#Интерфейс
--title=${filename} 
--osd-on-seek=no
--keep-open=no
--ontop=no
--osd-font-size=30
--osd-border-size=0.5
--osd-font=Inter
--autofit=60%x50%
--script-opts-append=osc-seekrangestyle=none
--force-media-title
--write-filename-in-watch-later-config
--osd-duration=3000
--osd-playing-msg = [${playlist-pos-1}/${playlist-count}]
--osd-playing-msg = ${osd-ass-cc/0}{\\an9}[${playlist-pos-1}/${playlist-count}]
--osc=no







#Видео
--save-position-on-quit
--video-sync=audio
--priority=high
--video-output-levels=full
--hwdec=auto
--tone-mapping=bt.2446a
--vo=gpu-next
--hdr-compute-peak=auto
--hr-seek=yes
--osc=no
--scale=lanczos
--dscale=lanczos
--cscale=lanczos

--dither=no


#Cкриншоты
--screenshot-format=png
--screenshot-png-compression=1
--screenshot-png-filter=5
--screenshot-tag-colorspace=yes
--screenshot-high-bit-depth=no
--screenshot-template=mpv_%F_%p_%04n


#Аудио
--alang=rus,ru
--audio-file-auto=fuzzy
--audio-file-paths=**
--audio-channels=auto-safe
--ao=wasapi
--ad-lavc-downmix=no
--volume-max=150
--ad-lavc-threads=0



#Кеш
--cache=yes
--cache-secs=10





#Субтитры
--slang=rus,ru
--sub-ass-vsfilter-color-compat=full
--sub-auto=fuzzy
--sub-file-paths=**
--sub-font="calibri bold"
--sub-margin-y=50
--sub-font-size=50
--sub-color="#FFFFFFFF"
--sub-border-size=2
--sub-blur=1



#Изображения
--image-display-duration=inf

